### ISSUE TITLE
Adapter : filters and tags are read two times for each query

### ISSUE THREAD

**Issue by GohuHQ** [AnyBlok/anyblok-pyramid-rest-api#34]
https://github.com/AnyBlok/anyblok-pyramid-rest-api/blob/b0fcc7d7fc1b06536b31db85592cf9538d7afa71/anyblok_pyramid_rest_api/crud_resource.py#L53-L55

**Comment by jssuzanne** [comment]
thank, waiting the merge of the PR #35
