### ISSUE TITLE
Add primary_key filter in querystring

### ISSUE THREAD

**Issue by jssuzanne** [AnyBlok/anyblok-pyramid-rest-api#63]
The goal is to add a filter for the multi primary key

For example, filtering on the **Model.System.Field** model can be dangerous if the we don't want the 'Model.System.Cache:id'.

With the classical querystring. we call api with `~filter[model][eq]=Model.Cache&~filter[name][eq]=id`

The equivalence with SQL is

```
anyblok=> select * from system_field where name='id';
 name |        code        |         model         | label |  ftype  |     entity_type     
------+--------------------+-----------------------+-------+---------+---------------------
 id   | system_cache.id    | Model.System.Cache    | Id    | Integer | Model.System.Column
 id   | system_sequence.id | Model.System.Sequence | Id    | Integer | Model.System.Column
(2 lignes)

anyblok=> select * from system_field where model='Model.System.Cache';
     name      |            code            |       model        |     label     |  ftype  |     entity_type     
---------------+----------------------------+--------------------+---------------+---------+---------------------
 id            | system_cache.id            | Model.System.Cache | Id            | Integer | Model.System.Column
 registry_name | system_cache.registry_name | Model.System.Cache | Registry name | String  | Model.System.Column
 method        | system_cache.method        | Model.System.Cache | Method        | String  | Model.System.Column
(3 lignes)



anyblok=> select count(*) from system_field ;
 count 
-------
    49
(1 ligne)

anyblok=> select count(*) from system_field where name!='id' and model!='Model.System.Cache';
 count 
-------
    45
(1 ligne)

```

This method not exclude only **Model.System.Cache:id** but also **Model.System.Sequence:id** and all columns on **Model.System.Cache**

the good implementation should be

```
anyblok=> select count(*) from system_field where not(name='id' and model='Model.System.Cache');
 count 
-------
    48
(1 ligne)

```

The query string should look like `~primary-keys[model,name]=Model.System.Cache:id`. We also define that this entry can be receive multiple values `primarykeys[model:name]=Model.System.Cache:id,Model.System.Blok:name,Model.System.Model:name`

- [ ] **include mode** : primary-keys[key1:key2:...,keyn]=value1:value2:...:valuen
- [ ] **exclude mode** : ~primary-keys[key1:key2:...:keyn]=value1:value2:...:valuen
- [ ] keys are only a real primary_key on the model
- [ ] no relationship
- [ ] allow to define more than on primary-keys

In this case the exclude mode do a 'AND' between where clause and the include mode do a 'OR'

- [ ] **include mode** do a OR between pirmary keys
- [ ] **exclude mode** do a AND between pirmary keys

**Comment by petrus-v** [comment]
as long #65 is merged I'm closing this issue
